wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.4
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.0
    start_time: 1666171890.218556
    t:
      1:
      - 1
      - 40
      - 41
      - 55
      2:
      - 1
      - 40
      - 41
      - 55
      3:
      - 1
      - 16
      - 17
      - 23
      - 37
      4: 3.9.0
      5: 0.13.4
      8:
      - 5
      10:
      - 3
batch_size:
  desc: null
  value: 32
cache_type:
  desc: null
  value: full
channel_dim:
  desc: null
  value: 512
dataroot:
  desc: null
  value: /home3/theanhtran/02_subject/Segmentation/Vision-Language-Transformer
dcrf:
  desc: null
  value: false
dropout:
  desc: null
  value: 0.3
epochs:
  desc: null
  value: 30
feature_dim:
  desc: null
  value: 14
gamma:
  desc: null
  value: 0.7
glove_path:
  desc: null
  value: <glove_path>
grad_check:
  desc: null
  value: false
image_dim:
  desc: null
  value: 448
image_encoder:
  desc: null
  value: resnet50
loss:
  desc: null
  value: bce
lr:
  desc: null
  value: 0.0003
mask_dim:
  desc: null
  value: 56
model_dir:
  desc: null
  value: ./saved_model
model_filename:
  desc: null
  value: model_unc.pth
num_encoder_layers:
  desc: null
  value: 2
num_layers:
  desc: null
  value: 1
num_workers:
  desc: null
  value: 4
optimizer:
  desc: null
  value: AdamW
phrase_len:
  desc: null
  value: 20
run_name:
  desc: null
  value: run1
save:
  desc: null
  value: false
sfm_dim:
  desc: null
  value: 256
task:
  desc: null
  value: unc
threshold:
  desc: null
  value: 0.4
weight_decay:
  desc: null
  value: 0.001
